---
- name: NTP Server list
  nxos_template:
    src: create_ntp.j2
    provider: "{{ cli }}"
  register: output

- name: debug
  debug: var=output


- name: SNMP settings
  nxos_template:
    src: create_snmp.j2
    provider: "{{ cli }}"
  register: output

- name: debug
  debug: var=output
